name: mruby
title: Lightweight Ruby
description: >- # this means to ignore newlines until "markdown:"
  mruby is the lightweight implementation of the Ruby language complying to (part of) the ISO standard.
  mruby can be linked and embedded within your application. We provide the interpreter program "mruby" and the
  interactive mruby shell "mirb" as examples. You can also compile Ruby programs into compiled byte code using the
  mruby compiler "mrbc". All those tools reside in the "bin" directory. "mrbc" is also able to generate compiled byte
  code in a C source file, see the "mrbtest" program under the "test" directory for an example.
markdown: kramdown
highlighter: rouge
url: https://mruby.org
repository: https://github.com/mruby/mruby.github.io
include: _index.html
exclude:
  - CODEOWNERS
  - Gemfile
  - Gemfile.lock
  - README.md
  - gen_mgemdata.rb
  - gen_mrbdoc.rb
  - vendor
